### ISSUE TITLE
Hi from OMB

### ISSUE THREAD

**Issue by OldMansBeard** [plenarius/cleanmodels#1]
Just wanted to say "Hi" and thank you for taking CM3 on and dragging it screaming into the next decade :)

I left NWN years ago and haven't looked at NWN-EE at all, but I can see from your changes that the models have evolved slightly. But I guess they still have some of the old bugs :D  I remember the tilesets from SoU were particularly bad.

Feel free to email me on oldmansbeard AT pm DOT me if you want to make contact.

**Comment by plenarius** [comment]
Hey OMB!! I'm so sorry for the extremely delay in my reply. My life got busy too soon after I released this with a new career and company and it had to collect some dust. I just noticed you posted this issue though and I want to thank you for your wonderful tool and I was happy to catch it up a bit to speed and learn a bit about Prolog. I went in completely newb with Prolog and it was fun to learn a bit about it as I got the tool up to speed =) Hope things are great in your corner of the world!

**Comment by OldMansBeard** [comment]
Hi. I'm impressed that you could learn Prolog enough to unravel my spaghetti code, so well done. To be honest, I don't think I could have done what you've done, myself, now. After a few years, you forget how old software works and even though I still have my old working notes, as the saying goes, you can't step into the same river twice.

For me, the most interesting part of developing CM3 wasn't so much the coding but collecting the types of errors that needed to be fixed in models. I had a mixed background in Software Reliability as well as AI research and CM3 was a way of combining the two in an amusing way. But it was born of necessity and was a thing of its time - I couldn't do it again.

Anyway, good luck with your new career. You may not be using Prolog but remember the mindset that it flows from. Expressing problems in a Prolog-esque way can sometimes bring extra insight.

OMB
